AWSTemplateFormatVersion: 2010-09-09
Description: Cloud Foundations on AWS - Management Account Identity Center Assignments.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Identity Center Details"
        Parameters:
          - pIdentityCenterArn
      - Label:
          default: "Management Account Admin User Assignment"
        Parameters:
          - pMAAdministratorUserId
          - pMAAdministratorPermissionSetArn
      - Label:
          default: "Management Account ReadOnly User Assignment"
        Parameters:
          - pMAReadOnlyUserId
          - pMAReadOnlyPermissionSetArn
    ParameterLabels:
      pIdentityCenterArn:
        default: "AWS Identity Center Instance ARN"
      pMAAdministratorUserId:
        default: "MA Administrator User Id"
      pMAAdministratorPermissionSetArn:
        default: "MA Administrator Permission Set ARN"
      pMAReadOnlyUserId:
        default: "MA Read Only User Id"
      pMAReadOnlyPermissionSetArn:
        default: "MA ReadOnly Permission Set ARN"

Parameters:
  pIdentityCenterArn:
    Type: String
    Description: 'The Identity Center instance ARN'
  pMAAdministratorUserId:
    Type: String
    Description: 'The MA-Administrator Identity Center User Id (example: 92670cccd8-6c7550b2-66ea-4c80-a7f5-7929bd561793)'
  pMAAdministratorPermissionSetArn:
    Type: String
    Description: 'The ARN of the Administrator permission set to assign the user'
  pMAReadOnlyPermissionSetArn:
    Type: String
    Description: 'The ARN of the Read Only permission set to assign the user'
  pMAReadOnlyUserId:
    Type: String
    Description: 'The MA-ReadOnly Identity Center User Id (example: 92670cccd8-6c7550b2-66ea-4c80-a7f5-7929bd561793)'

Resources:
  rMAAdministratorUserAssignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref pIdentityCenterArn
      PermissionSetArn: !Ref pMAAdministratorPermissionSetArn
      TargetId: !Ref "AWS::AccountId"
      TargetType: "AWS_ACCOUNT"
      PrincipalType: "USER"
      PrincipalId: !Ref pMAAdministratorUserId

  rMAReadOnlyUserAssignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref pIdentityCenterArn
      PermissionSetArn: !Ref pMAReadOnlyPermissionSetArn
      TargetId: !Ref "AWS::AccountId"
      TargetType: "AWS_ACCOUNT"
      PrincipalType: "USER"
      PrincipalId: !Ref pMAReadOnlyUserId
