name: Bug Report
description: Report a bug
title: "(name): short issue description"
labels: ['type:bug', 'status:needs-triage']
body:
  - type: textarea
    id: problem
    attributes:
      label: What is the problem?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        1. Example template that results in the error
        2. The commands you used to invoke the tool
        3. The output received
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **NOTE: Please be sure that the templates, rules and logs you provide as part of your bug report do not contain any sensitive information.**

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: |
        What were you trying to achieve by performing the steps above?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: What actually happened?
      description: |
        What is the unexpected behavior you were seeing? If you got an error, paste it here.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: version of IaC or CLI being used
      description: Output
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Other information
      description: |
        e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

        This is :bug: Bug Report