name: Generate XLS Workbook from CFA Lens

on: 
  push:
    
jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f custom-lens/tools/python/requirements.txt ]; then pip install -r custom-lens/tools/python/requirements.txt; fi
        
    - name: Convert YAML to JSON
      run: |
        yq -p json -o yaml custom-lens/yaml/cloud-foundations-accelerator-custom-lens.yaml > custom-lens/cloud-foundations-accelerator-custom-lens.json
    
    - name: Generate XLS from a JSON
      run: python custom-lens/tools/python/json-2-xls.py -s custom-lens/cloud-foundations-accelerator-custom-lens.json -d custom-lens/cloud-foundations-accelerator-workbook.xlsx
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Add XLSX file created by GitHub Action"
        git push
